N-gramas(n-grams)

In [10]:
frase = "Ele sabia que eu sabia trabalhar com IA e sabia que eu estava estudando tecnologia sabia trabalhar"

In [11]:
# split transforma uma frase em uma lista de palavras
palavras = frase.split()
palavras

['Ele',
 'sabia',
 'que',
 'eu',
 'sabia',
 'trabalhar',
 'com',
 'IA',
 'e',
 'sabia',
 'que',
 'eu',
 'estava',
 'estudando',
 'tecnologia',
 'sabia',
 'trabalhar']

In [12]:
import pandas as pd
tabela = pd.DataFrame({"palavras":palavras})
tabela

      palavras
0          Ele
1        sabia
2          que
3           eu
4        sabia
5    trabalhar
6          com
7           IA
8            e
9        sabia
10         que
11          eu
12      estava
13   estudando
14  tecnologia
15       sabia
16   trabalhar

In [13]:
tabela ["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

      palavras proxima_palavra
0          Ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia       trabalhar
5    trabalhar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia       trabalhar
16   trabalhar            None

In [14]:
tabela = tabela.dropna()
tabela

      palavras proxima_palavra
0          Ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia       trabalhar
5    trabalhar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia       trabalhar

In [30]:
filtro = tabela["palavras"] == "sabia"
tabela[filtro]

   palavras proxima_palavra
1     sabia             que
4     sabia       trabalhar
9     sabia             que
15    sabia       trabalhar

In [31]:
tabela[filtro]["palavras"].value_counts()

palavras
sabia    4
Name: count, dtype: int64

In [32]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
que          0.5
trabalhar    0.5
Name: proportion, dtype: float64

In [33]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'que'

In [34]:
filtro = tabela["palavras"] == "que"
tabela[filtro]

   palavras proxima_palavra
2       que              eu
10      que              eu

In [35]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
eu    1.0
Name: proportion, dtype: float64

In [36]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'eu'