In [2]:
arquivo = open(r".\data\dom_casmurro.txt", encoding="utf-8" )

texto = arquivo.read()
len(texto)

381375

In [3]:
palavras = texto.split()
len(palavras)

65707

In [4]:
import pandas as pd
tabela = pd.DataFrame({"palavras":palavras})
tabela

       palavras
0           DOM
1      CASMURRO
2           POR
3       MACHADO
4            DE
...         ...
65702         É
65703      bem,
65704         e
65705         o
65706    resto?

[65707 rows x 1 columns]

In [5]:
tabela ["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?
65706    resto?            None

[65707 rows x 2 columns]

In [6]:
tabela = tabela.dropna()
tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65701   CXLVIII               É
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [51]:
filtro = tabela["palavras"] == "travêssa"
tabela[filtro]

       palavras proxima_palavra
47137  travêssa               e

In [40]:
tabela[filtro]["palavras"].value_counts()

palavras
que    2519
Name: count, dtype: int64

In [52]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
e    1.0
Name: proportion, dtype: float64

In [53]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'e'

In [54]:
print("Escobar e o que me não me não")
print("menina travêssa e o que me não ")

Escobar e o que me não me não
menina travêssa e o que me não